Simpler examples of concurrency primitives
typelevel/fs2 pull request #2237
Opened 2021-01-30 12:07 UTC by LLCampos

Didn't add an example for Queue because [it is being moved to cats-effect](https://github.com/typelevel/fs2/issues/2213). :)

2021-01-30 13:47 UTC, mpilquist requested changes
Thanks for working on docs! Added a couple comments about how we're targeting CE3/FS2 3.x now.

We could add docs on `Queue` too, given that FS2 has some methods for working with `cats.effect.std.Queue` -- e.g., `Stream.fromQueueNoneTerminated` being the most common.

2021-01-30 13:47 UTC, mpilquist commented on site/concurrency-primitives.md
> +```scala
If you change this to `scala mdoc`, the example will get compiled/tested as part of site generation. In this case, it'll show that the example is using the old CE2 / FS2 2.x API and hence needs to be updated for CE3 / FS2 3.x.

2021-01-30 13:47 UTC, mpilquist commented on site/concurrency-primitives.md
> +```scala
Same as above, needs updates for CE3

2021-01-30 18:22 UTC, diesalbla approved these changes
Thanks!

2021-01-31 11:57 UTC, LLCampos commented
@mpilquist, adapted things for CE3/FS2 3.x. Should I also change the branch this is being merge into? :thinking:

2021-01-31 12:16 UTC, LLCampos commented
Hm... CI workflow failed... is this expected?

2021-01-31 13:58 UTC, ritschwumm commented on site/concurrency-primitives.md
> +val topic: IO[Topic[IO, String]] = Topic("Topic start")(Concurrent[IO])
imho typeclass instances should never be passed around manually, except as a workaround where more than one instance exists. especially not in example code that will be widely copied.
if it works, i'd suggesst writing `Topic[IO,String](...)` instead.

2021-02-06 15:55 UTC, merged